import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BusFront, Check, Clock3, Menu, MessageCircle, Users, X } from 'lucide-react';
import './styles.css';

// Replace this one value with the company's WhatsApp number, including country code, without + or spaces.
const config = { whatsappPhone: '96103252660', instagram: '#', facebook: '#', phoneLabel: '03 252 660 · 03 129 780', name: 'Boustany Transportation' };
const wa = (message = 'Hello, I would like information about your trips across Lebanon.') => `https://wa.me/${config.whatsappPhone}?text=${encodeURIComponent(message)}`;
const images = {
  logo: 'https://ksubsviatxrqfjdgreca.supabase.co/storage/v1/object/public/Boustany%20photos/logbustany.png',
  logoMini: 'https://ksubsviatxrqfjdgreca.supabase.co/storage/v1/object/public/Boustany%20photos/minilogbustany.png',
  hero: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1800&q=85',
  bekaa: 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1000&q=80',
  byblos: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1000&q=80',
  tripoli: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1000&q=80',
  mountain: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',
  sea: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80',
  bus: 'https://ksubsviatxrqfjdgreca.supabase.co/storage/v1/object/public/Boustany%20photos/busAlbustany.jpg',
};

function WhatsApp({ children, className = '' }) { return <a className={`button whatsapp ${className}`} href={wa()} target="_blank" rel="noreferrer"><MessageCircle size={18} />{children}</a>; }
function Header({lang,setLang}) { const [open, setOpen] = useState(false); const ar=lang==='ar'; return <header className="header"><div className="nav wrap"><a className="brand" href="#home"><img className="brand-logo" src={images.logoMini} alt={config.name}/><span>{config.name}</span></a><button className="language" onClick={()=>setLang(ar?'en':'ar')}>{ar?'English':'العربية'}</button><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button><nav className={open ? 'open' : ''}><a href="#home" onClick={() => setOpen(false)}>{ar?'الرئيسية':'Home'}</a><a href="#about" onClick={() => setOpen(false)}>{ar?'من نحن':'About us'}</a><WhatsApp>{ar?'واتساب':'WhatsApp us'}</WhatsApp></nav></div></header> }
const destinations = [{ title:'Bekaa Valley', text:'The heart of our routes, surrounded by open landscapes and mountain views.' }, { title:'Beirut', text:'Connect with Lebanon’s vibrant capital from the Bekaa and beyond.' }, { title:'Jbeil / Byblos', text:'A historic coastal destination full of character.' }, { title:'Tripoli', text:'Discover the culture and coastline of northern Lebanon.' }, { title:'Zahle', text:'Comfortable trips to and from the Bekaa’s beloved city.' }, { title:'Baalbek', text:'Reach one of Lebanon’s most important historic sites.' }, { title:'Sidon / Saida', text:'Travel south to the coast and its historic old city.' }, { title:'Tyre / Sour', text:'Plan a comfortable journey to Lebanon’s southern coast.' }, { title:'Mount Lebanon', text:'Ask us about routes through the mountain towns.' }, { title:'Any destination', text:'Tell us where you need to go and we’ll help plan the ride.' }];
const services = [{ icon:<BusFront/>, title:'School transportation', arTitle:'نقل للطلاب والمدارس', text:'Safe, dependable rides for students and school groups.', arText:'نقل آمن وموثوق للطلاب والمجموعات المدرسية.' }, { icon:<Users/>, title:'School visits', arTitle:'زيارات ورحلات مدرسية', text:'Comfortable transportation for educational trips and visits.', arText:'حافلات مريحة للزيارات والرحلات التعليمية.' }, { icon:<Users/>, title:'Tourist and group trips', arTitle:'رحلات سياحية ومجموعات', text:'Move together for tours, outings, and events across Lebanon.', arText:'منوصّلكن سوا بالرحلات والنزهات والمناسبات بكل لبنان.' }, { icon:<Clock3/>, title:'Private transportation', arTitle:'نقل خاص', text:'Choose the right bus for your group, occasion, or route.', arText:'اختاروا الباص المناسب لمجموعتكم أو مناسبتكم أو مشواركم.' }];
function App() { const [lang,setLang]=useState('ar'); const ar=lang==='ar'; const tx=ar?{ey:'بوستاني للنقل',hero:'مشوارك بكل لبنان.',copy:'نقل مريح وموثوق للطلاب والمدارس والمجموعات، من البقاع لبيروت ولكل المناطق اللبنانية.',comfort:'باصات مكيّفة بالكامل • راحة بكل مشوار',contact:'تواصل معنا عبر واتساب',introEy:'وين ما أخدك الطريق',intro:'روح أبعد.\nوخليك مرتاح.',introCopy:'نحنا شركة نقل محلية عنا تشكيلة باصات للطلاب والمدارس والرحلات والمجموعات، مع راحة واهتمام بكل مشوار.',destEy:'اكتشفوا لبنان',dest:'وجهاتنا',destCopy:'من الوادي عالساحل، خبرونا عن رحلتكم الجاية.',serviceEy:'خدماتنا',service:'نقل مريح\nللجميع.',fleetEy:'حافلاتنا',fleet:'أسطول جاهز\nللطريق.',fleetCopy:'عنا مجموعة متنوعة من الباصات والميني باص، جاهزة للنقل المدرسي والزيارات والرحلات والمناسبات.',contactEy:'خلّينا نخطط لمشواركم الجايي',contactTitle:'لوين\nحابّين تروحوا؟',contactCopy:'اسألونا عن باصات الطلاب، الزيارات المدرسية، الوجهات، المواعيد والأسعار. منكون مبسوطين نساعدكم.',chat:'احكوا معنا عبر واتساب',phone:'هاتف',insta:'إنستغرام',facebook:'فيسبوك',transport:'نقل بكل أنحاء لبنان.'}:{ey:'BOUSTANY TRANSPORTATION',hero:'Your ride across Lebanon.',copy:'Comfortable, dependable transportation for students, schools, groups, and destinations throughout Lebanon.',comfort:'Fully air-conditioned buses • Comfort on every journey',contact:'Contact us on WhatsApp',introEy:'WHEREVER THE ROAD LEADS',intro:'Go further.\nFeel at home.',introCopy:'We are a local transportation company with a range of buses for students, schools, tours, and groups—with comfort and care.',destEy:'EXPLORE LEBANON',dest:'Popular destinations',destCopy:'From the valley to the coast, ask us about your next trip.',serviceEy:'WHAT WE DO',service:'Made for moving\ntogether.',fleetEy:'OUR BUSES',fleet:'A fleet ready\nfor the road.',fleetCopy:'We have a collection of buses and minibuses ready for school transportation, school visits, tours, events, and private trips.',contactEy:'LET’S PLAN YOUR NEXT TRIP',contactTitle:'Where do you\nwant to go?',contactCopy:'Ask us about student buses, school visits, destinations, schedules, and prices. We’ll be happy to help.',chat:'Chat with us on WhatsApp',phone:'Phone',insta:'Instagram',facebook:'Facebook',transport:'Transportation across Lebanon.'}; return <div dir={ar?'rtl':'ltr'}><Header lang={lang} setLang={setLang}/><main id="home"><section className="hero"><div className="hero-image"/><div className="hero-content wrap"><p className="eyebrow light">{tx.ey}</p><h1>{tx.hero}</h1><p className="hero-copy">{tx.copy}</p><p className="comfort-line">{tx.comfort}</p><div className="actions"><WhatsApp>{tx.contact}</WhatsApp></div></div><div className="hero-note"><span>01</span><span className="line"/><span>{ar?'طرق بتستاهل التجربة':'Roads worth taking'}</span></div></section>
<section className="intro wrap" id="about"><div><p className="eyebrow">{tx.introEy}</p><h2>{tx.intro.split('\n').map((x,i)=><React.Fragment key={x}>{i>0&&<br/>}<em>{x}</em></React.Fragment>)}</h2></div><div className="intro-copy"><p>{tx.introCopy}</p></div></section>
<section className="section wrap" id="destinations"><div className="section-heading"><div><p className="eyebrow">{tx.destEy}</p><h2>{tx.dest}</h2></div><p>{tx.destCopy}</p></div><div className="map-layout"><div className="lebanon-map"><img src="https://upload.wikimedia.org/wikipedia/commons/d/db/Lebanon.geohive.gif?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=original" alt="Map of Lebanon"/></div><div className="city-list">{destinations.map((d,i)=><div className="city-row" key={d.title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{d.title}</h3><p>{d.text}</p></div></div>)}</div></div></section>
<section className="services section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">{tx.serviceEy}</p><h2>{tx.service.split('\n').map((x,i)=><React.Fragment key={x}>{i>0&&<br/>}<em>{x}</em></React.Fragment>)}</h2></div></div><div className="service-grid">{services.map(s=><div className="service" key={s.title}><div className="service-icon">{s.icon}</div><h3>{ar?s.arTitle:s.title}</h3><p>{ar?s.arText:s.text}</p></div>)}</div></div></section>
<section className="fleet wrap" id="our-buses"><div className="fleet-photo"><img src={images.bus} alt="Passenger bus"/><span>BOUSTANY TRANSPORTATION</span></div><div className="fleet-copy"><p className="eyebrow">{tx.fleetEy}</p><h2>{tx.fleet.split('\n').map((x,i)=><React.Fragment key={x}>{i>0&&<br/>}<em>{x}</em></React.Fragment>)}</h2><p>{tx.fleetCopy}</p><div className="check"><Check size={17}/> {ar?'راحتكم أولويتنا':'Your comfort comes first'}</div><div className="check"><Check size={17}/> {ar?'فريق محلي يمكنكم التواصل معه':'A local team you can reach directly'}</div></div></section>
<div className="quick-whatsapp"><WhatsApp>{ar?'واتساب':'WhatsApp'}</WhatsApp></div></main><footer><div className="wrap footer-grid"><a className="brand" href="#home"><img className="brand-logo" src={images.logo} alt={config.name}/><span>{config.name}</span></a><p>{tx.transport}</p></div><div className="wrap copyright">© 2026 {config.name}</div></footer></div> }
createRoot(document.getElementById('root')).render(<App/>);
